### ISSUE TITLE
about gene length and effective gene length

### ISSUE THREAD

**Issue by qliugithub** [andysaurin/tpm_rpkm#1]
Here's a mistake.
lengths = ftr.cnt[,6]  was means the whole gene length of per  gene , instead of the whole exon length per gene . So we should calculate the right length of the all exon length of per gene.

**Comment by andysaurin** [comment]
lengths = ftr.cnt[,6] is the sum of all the exons for that transcript ie the spliced transcript length (6th column in featurecounts output). This is what RPKM and TPM uses, not the gene length, unless I'm missing something
